# Generated by Django 2.2.7 on 2019-11-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='address',
            field=models.CharField(choices=[('Noida HQ', '<random_address1>'), ('Bangalore', '<random_address2>')], default='Noida HQ', max_length=100),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='check_out_time',
            field=models.TimeField(),
        ),
    ]
