# Generated by Django 2.2.7 on 2019-11-21 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_auto_20191121_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(max_length=13),
        ),
    ]
