# Generated by Django 2.2.7 on 2019-11-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20191121_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='check_out_time',
            field=models.DateTimeField(),
        ),
    ]
